nonnymoose/xsr

README.md

Note Ctrl+C quit ability in README.md

---

xsr

They enable or disable the countdown
Resolves #21 .

Add the --countdown and --nocountdown options

---

README.md
xsr

If supplied, xsr will not add the mouse cursor to screenshots.
Resolves #19 .

Add the --no-mouse option

---

README.md
xsr

Add the ability to specify countdown duration

---

xsr

This makes it easier to add new options.
Resolves #33 .

Move the GetOptions call to multiple lines

---

xsr

Still does not f i x (Github, don't close the issue) #27, but now slightly better
This should increase some the stability of the program.

Save in $tmpdir/tmpencoded.html

---

xsr

Also fixed tab length on --no-countdown

Condense help option into a subroutine

---

xsr

 Add --quiet|-q option

---

xsr

 Print out accepted filetypes if the user gets it wrong

---

xsr

Wrap biggest possible feature detection block in if (not $nomouse)

---

xsr

Assertions for file operations

---

README.md

Add info message about shift in break

---

Makefile
README.md
README.md.m4
markdown-preset.m4

Create make rule for README.md

---

README.md
README.md.m4

Add informational message about the `Break` button

---

xsr

Use array instead of file for storing mousegrabs

---

xsr

It should be ready!
@lezsakdomi, could you look over the code and test it too? I want to make sure I didn't miss anything when testing.
Once merged, this will finally resolve #5.

Integrate compatibility for strict mode

---

.travis.yml
Makefile

Fixes #67
Needs actions out of git code:
- Enabling Travis on this repo
- Creating a machine user, and
- Generating an oauth token with R/W acces to this repository
- Setting this token as a secret environment variable in Travis

Use Travis CI

---

xsr

Use UTF-8 everywhere

---

xsr

Add application titles

---

README.md
xsr

Provide command-line option for locating Cursor.png and check if that really exists.
Solves #80

Hotfix for #80
